### ISSUE TITLE
Change spelling

### ISSUE THREAD

**Issue by jhollist** [noreastrconf/hex_logo#2]
So, one thing I noticed is that we had the spelling a bit off if we really want to play on the Nor'easter theme.

I changed spelling on the website to Nor'eastR, close to the original spelling and emphasizes the R connection.  Any chance you could update the images on here, @haozhu233 ?

**Comment by haozhu233** [comment]
@jhollist I almost missed this issue in all my github notification emails! 😂I need to clean them up...

I just pushed the updates to this repo. Please take a look.

**Comment by jhollist** [comment]
No problems at all and I think it looks great!

Will close this now.  Thanks.
