### ISSUE TITLE
Single or Two Color logo?

### ISSUE THREAD

**Issue by jhollist** [noreastrconf/hex_logo#3]
@haozhu233 any chance you could throw together a two color version of the logo?  We are going to use it on some mugs and the gradient and background snow flakes are going to cause some problems (mostly financial!) with the printing.  A single or two color logo without the snowflakes would solve a lot of that.

I'd attempt it myself, but I have nearly zero experience working with svgs...

**Comment by haozhu233** [comment]
@jhollist no worries. I will make the change later today. :)

**Comment by jhollist** [comment]
Awesome!

**Comment by haozhu233** [comment]
@jhollist I just added some single color logos. Hope it works!
