### ISSUE TITLE
URL on edge: drop or increase font size

### ISSUE THREAD

**Issue by jhollist** [noreastrconf/hex_logo#4]
@haozhu233 Another change to request.

We are getting hex stickers made and Sticker Mule wants the text of the URL on the edge to be at least 6pt font.  So we need to increase the size we have now or if it is easier we can just drop the URL for the hex stickers...

THanks!

**Comment by haozhu233** [comment]
@jhollist Ah, I just noticed this issue. Do you still need me to increase the font size?

**Comment by jhollist** [comment]
All set.  I just edited it out on the png.

Thanks!

**Comment by haozhu233** [comment]
👍👍
